CREATE TABLE DEPARTMENT
(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(100),
DEPT_LOCATION VARCHAR(100)
);

INSERT INTO DEPARTMENT VALUES(1,'IT','PUNE');
INSERT INTO DEPARTMENT VALUES(2,'HR','MUMBAI');
INSERT INTO DEPARTMENT VALUES(3,'ADMIN','MUMBAI');
INSERT INTO DEPARTMENT VALUES(4,'SECURITY','PUNE');
INSERT INTO DEPARTMENT VALUES(5,'FINANCE','MUMBAI');


select * from department;

CREATE TABLE EMPLOYEES
(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(100),
JOB_NAME VARCHAR(100),
HIRE_DATE DATE,
SALARY DECIMAL(10,2),
COMMISSION DECIMAL(7,2),
DEPT_ID INT,
 FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

INSERT INTO EMPLOYEES VALUES (1,'SUNIL','MANAGER','10/10/2018',60001,1000,1);
INSERT INTO EMPLOYEES VALUES (2,'KAPIL','MANAGER','05/10/2018',80012,1000,2);
INSERT INTO EMPLOYEES VALUES (3,'SAMIR','CLERK','10/10/2018',11000,1000,2);
INSERT INTO EMPLOYEES VALUES (4,'KRUTIKA','CLERK','05/10/2018',12000,1000,2);
INSERT INTO EMPLOYEES VALUES (5,'YASIKA','CLERK','10/10/2019',13000,5000,2);
INSERT INTO EMPLOYEES VALUES (6,'SONAL','CLERK','05/10/2019',14000,6000,2);

select * from department;
select * from employees;


CREATE TABLE COUNTRY(COUNTRYID INT PRIMARY KEY,
COUNTRYNAME VARCHAR(100),
COUNTRYCAPITAL VARCHAR(100));

ALTER TABLE COUNTRY ADD FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEES(EMP_ID);


CREATE TABLE STATES(STATEID INT PRIMARY KEY,
STATENAME VARCHAR(100),
STATECAPITAL VARCHAR(100),
COUNTRYID INT,
FOREIGN KEY(COUNTRYID) REFERENCES COUNTRY(COUNTRYID));

CREATE TABLE CITY(CITYID INT PRIMARY KEY,
CITYNAME VARCHAR(100),
STATEID INT,
FOREIGN KEY(STATEID) REFERENCES STATES(STATEID));

INSERT INTO COUNTRY VALUES(1,'INDIA','DELHI');
INSERT INTO STATES VALUES(1,'MH','MUMBAI',1);
INSERT INTO CITY VALUES(1,'MUMBAI',1);
INSERT INTO CITY VALUES(2,'PUNE',1);

SELECT * FROM DEPARTMENT INNER JOIN EMPLOYEES ON DEPARTMENT.DEPT_ID = EMPLOYEES.DEPT_ID  
						  INNER JOIN COUNTRY ON COUNTRY.EMP_ID  = EMPLOYEES.EMP_ID 
						  INNER JOIN STATES ON STATES.COUNTRYID = COUNTRY.COUNTRYID 
						  INNER JOIN CITY ON CITY.STATEID = STATES.STATEID;


SELECT EMP_NAME,  DEPT_NAME, DEPT_LOCATION, COUNT (EMP_ID) FROM DEPARTMENT 
	INNER JOIN EMPLOYEES ON DEPARTMENT.DEPT_ID = EMPLOYEES.DEPT_ID  
		GROUP BY EMP_NAME, DEPT_NAME, DEPT_LOCATION;


CREATE OR REPLACE PROCEDURE sp_calcu()
language plpgsql
as $$
declare 
	t int;
begin
	t := n1 /n2;
	raise notice 'total = %', t;
exception
	when others then 
		raise notice 'exception occured at %', SQLSTATE;
end; $$

call sp_calcu (10,0);



CREATE OR REPLACE PROCEDURE sp_in(n1 int, n2 int)
language plpgsql
as $$
declare 
	t int;
begin
	t := n1 /n2;
	raise notice 'total = %', t;
exception
	when others then 
		raise notice 'exception occured at %', SQLSTATE;
end; $$


CREATE TABLE ERRORLOGS (
ERRORID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
ERRORMSG VARCHAR (2000),
ERRORSTATE VARCHAR (2000),
ERRORGENERATEDBY VARCHAR (2000),
ERRORDATETIME TIMESTAMP
);

CREATE OR REPLACE PROCEDURE gen_log(n1 int, n2 int)
language plpgsql
as $$
declare 
	t int;
begin
	begin
	t := n1 /n2;
	raise notice 'total = %', t;
	exception
	when others then 
		raise notice 'exception occured at %', SQLSTATE;
		INSERT INTO ERRORLOGS(ERRORMSG,ERRORSTATE,ERRORGENERATEDBY,ERRORDATETIME) VALUES (SQLERRM,SQLSTATE,CURRENT_USER,NOW());
	END;
	 
	t := n1+n2;
	exception
	when others then 
		raise notice 'exception occured at %', SQLSTATE;
		INSERT INTO ERRORLOGS(ERRORMSG,ERRORSTATE,ERRORGENERATEDBY,ERRORDATETIME) VALUES (SQLERRM,SQLSTATE,CURRENT_USER,NOW());
end; $$

call gen_log (10,0);
SELECT * FROM ERRORLOGS;

CREATE OR REPLACE PROCEDURE SP_OUT (n1 int, n2 int, out t int)
language plpgsql
as $$
begin
t := n1+n2;
end; $$

do
$$
declare
 t int;
begin
call SP_OUT(10,20,t);
call SP_OUT1(t);
raise notice 'addition = %', t;
end;$$

CREATE OR REPLACE PROCEDURE SP_OUT1 (t int)
language plpgsql
as $$
begin
raise notice 'ddd - %',t;
end;$$

