CREATE TABLE GAMES (
game_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  PRIMARY KEY NOT NULL,
game_name varchar(100),
players int 
);

INSERT INTO GAMES (game_name, players) VALUES ('GTA', 32342546);
INSERT INTO GAMES (game_name, players) VALUES ('Spiderman-Remastered', 456776);
INSERT INTO GAMES (game_name, players) VALUES ('Call-of-duty', 3224566);

CREATE MATERIALIZED VIEW dis_games as (select * from GAMES);
Select * from dis_games;

CREATE TABLE students (
   student_id serial PRIMARY KEY,
   full_name VARCHAR NOT NULL,
   branch_id INT
);


INSERT INTO students (
    student_id,
    full_name,
    branch_id
)
VALUES
    (1, 'M.S Dhoni', NULL),
    (2, 'Sachin Tendulkar', 1),
    (3, 'R. Sharma', 1),
    (4, 'S. Raina', 1),
    (5, 'B. Kumar', 1),
    (6, 'Y. Singh', 2),
    (7, 'Virender Sehwag ', 2),
    (8, 'Ajinkya Rahane', 2),
    (9, 'Shikhar Dhawan', 2),
    (10, 'Mohammed Shami', 3),
    (11, 'Shreyas Iyer', 3),
    (12, 'Mayank Agarwal', 3),
    (13, 'K. L. Rahul', 3),
    (14, 'Hardik Pandya', 4),
    (15, 'Dinesh Karthik', 4),
    (16, 'Jasprit Bumrah', 7),
    (17, 'Kuldeep Yadav', 7),
    (18, 'Yuzvendra Chahal', 8),
    (19, 'Rishabh Pant', 8),
    (20, 'Sanju Samson', 8);

	Select * from students;
	
 -- cursor
do
$$
declare 
	my_cur CURSOR FOR SELECT student_id,full_name  FROM students;
	sid int;
	sname varchar(100);

Begin
	OPEN my_cur;
	fetch next from my_cur into sid,sname;
	loop
	raise notice 'ID = %  Name = %',sid,sname;
	fetch next from my_cur into sid,sname;
	exit when not found;
	end loop;
end;$$
