CREATE TABLE EMPLOYEES(
EMPID int,
EMPNAME varchar(100) NULL,
SALARY float NULL,
TAX float NULL,
DOJ date NULL,
DEPT varchar(100) NULL,
DESG varchar(100) NULL,
DEPTMANAGERNAME varchar(100) NULL,
DEPTLOCATION varchar(100) NULL);

INSERT into EMPLOYEES VALUES
(1,'AKASH', 70000, 2000,'2017-05-20','IT','SOFTWARE DEVELOPER', 'SURESH','PUNE'),
(2,'AKSHAY', 69000, 1900,'2017-07-14','IT','ARCHITECT','SURESH', 'PUNE'),
(3,'ASHWIN', 77000, 2100,'2017-09-14','IT','ARCHITECT','SURESH','PUNE'),
(4,'CHINMAY', 88000, 2900,'2017-09-10','HR','MANAGER','ANITA','MUMBAI'),
(5,'DEBAYAN', 65000, 2100, '2017-10-18','HR','EXECUTIVE','ANITA','MUMBAI'),
(6,'MANGESH', 99000, 2900,'2017-10-10','HR','MANAGER','ANITA','MUMBAI'),
(7,'NIKHIL', 56000, 2100,'2017-07-1','HR','EXECUTIVE','ANITA', 'MUMBAI'),
(10,'SANDEEP', 45000, 460,'2017-07-25', 'IT','SOFTWARE DEVELOPER','SURESH', 'PUNE')

SELECT* FROM EMPLOYEES ;



-- WRITE A QUERY TO FIND THE details of employee having the 3rd Higher Salary from the table

SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 1 OFFSET 2);


-- WRITE A QUERY TO FIND THE employee having the second lowest salary from the table.

SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC LIMIT 1 OFFSET 1);


-- WRITE A QUERY TO FIND THE details of employee having the 5th & 6th Higher Salary from the table

 WITH HIGHER_FIFTH_SIXTH AS (SELECT *, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS rank FROM EMPLOYEES)
 SELECT * FROM HIGHER_FIFTH_SIXTH WHERE rank IN (5,6);


 -- Write a query to find the details of employee having the lowest salary in each department

 SELECT e.DEPT, e.EMPID, e.EMPNAME, e.SALARY FROM EMPLOYEES e WHERE e.SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPT = E.DEPT);


 -- Write a CTE to find the details of employee having the 4 th Highest salary

 WITH HIGHER_FIFTH_SIXTH AS (SELECT *, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS rank FROM EMPLOYEES)
 SELECT * FROM HIGHER_FIFTH_SIXTH WHERE rank IN (4);

 -- Write a query to find the details of employee having 2 nd highest salary holder in each department.
  SELECT e.DEPT, e.EMPID, e.EMPNAME, e.SALARY FROM EMPLOYEES e WHERE e.SALARY = 
  (SELECT MAX(SALARY) FROM EMPLOYEES 
  	WHERE DEPT = E.DEPT AND SALARY < (
	  	SELECT MAX(SALARY) FROM EMPLOYEES
		  WHERE DEPT = e.DEPT ) 
  );

-- Write a stored procedure which will create two table from the single table (One is the department table and second is the employee table and create a relationship
-- between them). [Hint : Use temp tables if required) 

CREATE OR REPLACE PROCEDURE SP_CREATE_TABLE()
language plpgsql
AS $$
BEGIN
	CREATE TEMP TABLE T_DEPT AS SELECT DISTINCT DEPT AS DEPT_NAME, DEPTLOCATION AS DEPT_LOCATION FROM EMPLOYEES; 

	CREATE TABLE IF NOT EXISTS DEPARTMENT (
        DEPT_ID SERIAL PRIMARY KEY,
        DEPT_NAME VARCHAR(100) UNIQUE NOT NULL,
        DEPT_LOCATION VARCHAR(100)
    );
	INSERT INTO DEPARTMENT (DEPT_NAME, DEPT_LOCATION)
    SELECT DEPT_NAME, DEPT_LOCATION FROM T_DEPT;

	CREATE TABLE IF NOT EXISTS EMPLOYEE (
        EMPID INT PRIMARY KEY,
        EMPNAME VARCHAR(100) NOT NULL,
        SALARY FLOAT,
        TAX FLOAT,
        DOJ DATE,
        DESG VARCHAR(100),
        DEPT_ID INT REFERENCES DEPARTMENT(DEPT_ID)
    );

	INSERT INTO EMPLOYEE (EMPID, EMPNAME, SALARY, TAX, DOJ, DESG, DEPT_ID)
    SELECT e.EMPID, e.EMPNAME, e.SALARY, e.TAX, e.DOJ, e.DESG, d.DEPT_ID
    FROM EMPLOYEES e
    JOIN DEPARTMENT d ON e.DEPT = d.DEPT_NAME;
	
end;$$

call SP_CREATE_TABLE();

select * from  EMPLOYEE;
select * from DEPARTMENT;