CREATE TABLE emp1 (
empID int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  PRIMARY KEY NOT NULL,
empNAME VARCHAR(100),
gender VARCHAR(100),
sal real,
tax real,
dept varchar (100),
desg varchar(100)
);

SELECT * FROM emp1;

DROP TABLE emp1;

TRUNCATE emp1;

delete from emp1 where empID = 5;

INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Anurag', 'Male', 35000.25, 15000, 'IT' , 'software engineer');
INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Shravani', 'Female', 30000.25, 10000, 'HR' , 'Associate HR');
INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Soham', 'Male', 35000.25, 15000, 'IT' , 'software engineer');
INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Somedh', 'Male', 45000.25, 15000, 'IT' , 'software engineer');
INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Ramesh', 'Male', 55000.25, 15000, 'SALES' , 's-manager');
INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Ramesh', 'Male', 55000.25, 15000, 'SALES' , 's-manager');
INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Somedh', 'Male', 40000.25, 15000, 'IT' , 'software engineer');
INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Ramesh', 'Male', 55000.25, 15000, 'SALES' , 's-manager');
INSERT INTO emp1 (empname, gender, sal, tax, dept, desg) VALUES('Somedh', 'Male', 45000.25, 15000, 'IT' , 'software engineer');


select * from emp1

-- where
Select * from emp1 where sal > 30000.30;

Select *, (sal-tax) AS inhand_sal from emp1 where sal > 30000.30;

-- ORDER BY
SELECT * FROM emp1 ORDER BY empid DESC;


SELECT empname, sal FROM emp1 ORDER BY sal DESC OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY;

-- RANK
SELECT RANK() OVER(ORDER BY sal DESC), empname, sal FROM emp1;

-- Row_number
SELECT ROW_NUMBER() OVER(ORDER BY sal DESC), RANK() OVER(ORDER BY sal DESC), empname, sal FROM emp1;

-- DENSE_RANK
SELECT DENSE_RANK() OVER(ORDER BY sal DESC), RANK() OVER(ORDER BY sal DESC), empname, sal FROM emp1;

-- Partition by
SELECT ROW_NUMBER() OVER(partition by dept ORDER BY sal DESC),empname, dept, sal  from emp1;

SELECT ROW_NUMBER() OVER(partition by dept ORDER BY sal DESC) as rank ,empname, dept, sal  from emp1 where rank = 1;


-- write a query to find top salary holder in each dept only
SELECT empname, dept, sal  FROM (
SELECT empname, dept, sal, ROW_NUMBER() OVER(partition by dept ORDER BY sal DESC) )from emp1 ;


-- Aggragate functions along with group by
-- group by is similar to partition 

SELECT dept, SUM(sal) AS totlsal from emp1 GROUP BY dept;

delete from emp1 where empid NOT IN (SELECT MIN(empid) 
	from emp1 group by empname, gender, sal, tax, dept, desg);

-- rollup
-- for first column
SELECT gender , dept, count (empid) AS empcount 
	from emp1 group by ROLLUP (gender, dept); 

-- cube 
-- both the column
SELECT gender , dept, count (empid) AS empcount 
	from emp1 group by cube (gender, dept);




select * from country;

SELECT c.country_of_origin count (s.statename) as statec
	from country c left join state_of_c s ON c.cid = s.cid
	group by c.country;

-- write a query to find the number of city

SELECT country_of_origin, count (cityname) FROM country	INNER JOIN state_of_c ON country.cid = state_of_c.cid  INNER JOIN CITY ON CITY.sateid = state_of_c.sateid group by country_of_origin ;  


-- Like
-- for pattern matching

Select * FROM emp1 Where empname like 'S%';

-- in
Select * FROM emp1 Where dept in ('IT');

-- between
-- use to find the values in a range
Select * from emp1 where sal BETWEEN 40000 AND 55000.25;

-- permanant table
	-- they are permanant they can not be earesed it stored in the hard disk

-- Temp tables
	-- they are created and stored temporarily and are droped by database server autometicaly as soon as the session is closed
	-- syntax
		-- SELECT TEMP TABLE emp2(id int, name varchar(100));

	-- we can also conver temp table into permanant table
	-- we can also transfer data from temp to permanant

-- general rule	
	--  the column name should be unique otherwise it will show error


	


