CREATE TABLE GAMES (
game_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  PRIMARY KEY NOT NULL,
game_name varchar(100),
players int 
);

INSERT INTO GAMES (game_name, players) VALUES ('GTA', 32342546);
INSERT INTO GAMES (game_name, players) VALUES ('Spiderman-Remastered', 456776);
INSERT INTO GAMES (game_name, players) VALUES ('Call-of-duty', 3224566);

CREATE MATERIALIZED VIEW dis_games as (select * from GAMES);

Select * from dis_games;

refresh MATERIALIZED VIEW dis_games;

-- Stored procedure
CREATE OR REPLACE PROCEDURE CALCULATOR_SP(num1 float, num2 float)
language plpgsql
as $$
declare
	addsp float := num1 + num2;
	subsp float := num1 - num2;
	multisp float := num1 * num2;
begin
raise notice 'addition of tow number =%',addsp;
raise notice 'substraction of tow number =%',subsp;
raise notice 'multiplaction of tow number =%',multisp;
end;$$

call CALCULATOR_SP(10,20);


-- loop
CREATE OR REPLACE PROCEDURE multiplaction(num1 int )
language plpgsql
as $$
declare
	n1 int :=1;
	val1 int :=0;
begin
While (n1 <= 10) loop
	val1 = num1 * n1;
	raise notice '% * % = %', num1,n1,val1;
	n1 := n1+1;
end loop;
end;$$

call multiplaction(24)




-- conditional statement
CREATE OR REPLACE PROCEDURE sp_grd(per float)
language plpgsql
as $$
declare
	gread varchar(100):=' ';
begin
if (per >= 75) then 
	gread := 'DISTENCTION';
elseif (per >= 60) then 
	gread := 'FIRST CLASS';
elseif (per >= 50) then 
	gread := 'SECOND CLASS';
elseif (per >= 35) then 
	gread := 'THIRD CLASS';
else 
	gread := 'FAIL!';
end if;
end;$$


CREATE table students1 (
roll_num int primary key,
sname varchar(100),
eng_marks int ,
scn_marks int ,
math_marks int,
total_marks int  ,
percentage float,
gread varchar(100)
);

CREATE  OR REPLACE PROCEDURE cm()
language plpgsql
as $$
declare
total_marks int;
percentage float ;
gread varchar(100);
begin 
	update students1
	set
		total_marks = eng_marks + scn_marks + math_marks,
		percentage = total_marks/3;

		update students1
    	set 
		gread = CASE 
		When percentage >= 90 Then 
		'A'
		When percentage >= 60 Then 
		'B'
		When percentage >= 35 Then 
		'C'
		ELSE 'F'
		END;
	raise notice 'Total marks , Percentage and Grades have been calculated and updated';
END;$$

INSERT INTO students1 (roll_num, sname, eng_marks, scn_marks ,math_marks) VALUES (1, 'Anurag', 50, 70, 30);
CALL cm();

TRUNCATE students1;
DROP TABLE students1; 

SELECT * FROM students1;


