CREATE TABLE food_items (
fid int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  PRIMARY KEY NOT NULL,
food_name varchar(200),
b_price real
);

CREATE TABLE india_outlet(
ifid int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  PRIMARY KEY NOT NULL,
food_in_india varchar(200),
i_price real,
fid int,
CONSTRAINT fk_fid FOREIGN KEY (fid) REFERENCES food_items(fid)
);

CREATE TABLE Amazon_outlet(
afid int GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1)  PRIMARY KEY NOT NULL,
food_in_amazon varchar(200),
a_price real,
fid int,
CONSTRAINT fk_fid FOREIGN KEY (fid) REFERENCES food_items(fid)
);

CREATE TABLE money_entry(
custid int GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)  PRIMARY KEY NOT NULL,
cust_name varchar(100),
ifid int,
CONSTRAINT fk_ifid FOREIGN KEY (ifid) REFERENCES india_outlet(ifid),
afid int,
CONSTRAINT fk_afid FOREIGN KEY (afid) REFERENCES Amazon_outlet(afid),
amount real,
t_date DATE DEFAULT CURRENT_DATE,
loc varchar(100)
);

SELECT * FROM food_items;
INSERT INTO food_items(food_name, b_price) VALUES ('Paneer Tikka', 150);
INSERT INTO food_items(food_name, b_price) VALUES ('Andaa ghotala', 100);
INSERT INTO food_items(food_name, b_price) VALUES ('Chicken tandoori', 200);
INSERT INTO food_items(food_name, b_price) VALUES ('Thali', 70);

INSERT INTO india_outlet (food_in_india, i_price, fid) VALUES ('Paneer Tikka', 200,1);
INSERT INTO india_outlet (food_in_india, i_price, fid) VALUES ('Andaa ghotala', 150,2);
INSERT INTO india_outlet (food_in_india, i_price, fid) VALUES ('Chicken tandoori', 250,3);
INSERT INTO india_outlet (food_in_india, i_price, fid) VALUES ('Thali', 100,4);


INSERT INTO Amazon_outlet (food_in_amazon, a_price, fid) VALUES ('Paneer Tikka', 250,1);
INSERT INTO Amazon_outlet (food_in_amazon, a_price, fid) VALUES ('Andaa ghotala', 200,2);
INSERT INTO Amazon_outlet (food_in_amazon, a_price, fid) VALUES ('Chicken tandoori', 300,3);
INSERT INTO Amazon_outlet (food_in_amazon, a_price, fid) VALUES ('Thali', 140,4);


SELECT * FROM food_items INNER JOIN india_outlet ON food_items.fid = india_outlet.fid  INNER JOIN Amazon_outlet ON Amazon_outlet.fid = food_items.fid;

Select * from Amazon_outlet ;
drop table money_entry;

INSERT INTO money_entry (cust_name, ifid, amount, t_date, loc) VALUES ('Anurag',1,200,'2025-01-07','indai');
INSERT INTO money_entry (cust_name, ifid, amount, t_date, loc) VALUES ('Raj',1,200,'2025-01-10','indai');
INSERT INTO money_entry (cust_name, afid, amount, t_date, loc) VALUES ('Jhon',102,300,'2025-01-17','amazon');
INSERT INTO money_entry (cust_name, afid, amount, t_date, loc) VALUES ('dune',103,140,'2025-01-22','amazon');

Select * from money_entry;